In [61]:
from keras.layers import Input, Dense
from keras.models import Model
import matplotlib.pyplot as plt
import numpy as np
from keras import losses

In [2]:
#20,000 trials of 10 coin flips. 
coinFlips = np.random.binomial(1,.5,(20000,10))

NameError: name 'np' is not defined

In [98]:
def simpleAE(encoding_dim = 32, input_dim = 784):

    # this is our input placeholder
    input_img = Input(shape=(input_dim,))
    # "encoded" is the encoded representation of the input
    encoded = Dense(encoding_dim, activation='relu')(input_img)
    # "decoded" is the lossy reconstruction of the input
    decoded = Dense(input_dim, activation='sigmoid')(encoded)

    # this model maps an input to its reconstruction
    return Model(input_img, decoded)

In [94]:
autoEnc = simpleAE(9,10)
autoEnc.compile(optimizer='adadelta', loss='binary_crossentropy')

In [95]:
autoEnc.fit(coinFlips, coinFlips, epochs=100, batch_size=50,verbose=1)

Epoch 1/100
20000/20000 [==============================] - 1s 65us/step - loss: 0.5282
Epoch 2/100
20000/20000 [==============================] - 1s 56us/step - loss: 0.2536
Epoch 3/100
20000/20000 [==============================] - 1s 55us/step - loss: 0.1252
Epoch 4/100
20000/20000 [==============================] - 1s 54us/step - loss: 0.0768
Epoch 5/100
20000/20000 [==============================] - 1s 56us/step - loss: 0.0572
Epoch 6/100
20000/20000 [==============================] - 1s 56us/step - loss: 0.0469
Epoch 7/100
20000/20000 [==============================] - 1s 53us/step - loss: 0.0402
Epoch 8/100
20000/20000 [==============================] - 1s 55us/step - loss: 0.0355
Epoch 9/100
20000/20000 [==============================] - 1s 55us/step - loss: 0.0319
Epoch 10/100
20000/20000 [==============================] - 1s 58us/step - loss: 0.0290
Epoch 11/100
20000/20000 [==============================] - 1s 55us/step - loss: 0.0265
Epoch 12/100
20000/20000 [===============

In [97]:
print(coinFlips[1:2])
autoEnc.predict(coinFlips[1:2])

[[1 0 1 1 0 1 1 1 0 0]]


array([[9.9999583e-01, 3.5516128e-05, 1.0000000e+00, 9.9999988e-01,
        2.4952394e-08, 9.9998283e-01, 9.9999678e-01, 9.9989140e-01,
        5.4280762e-09, 1.0010389e-05]], dtype=float32)

In [80]:
coinFlips = np.random.binomial(1,.5,(20000,10))

array([[1, 1, 1, 1, 1, 1, 0, 1, 1, 1]])